appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: FARtXCEz4pstnEKTv0TNU1sOHCFK0QYTeYZpTLIKWimrd8ku9i76OEgE2JUPB84zsGKwltckAq/98OU7dIdZMCJpP5jXAD7CZhBY0eq38qCZHbJk296R1Rzq6vL65N/Dh3DBcutKJWP1rxAxVYsWXFoAkjUFqBFeIVGdYPSWW2GIoO2HdM9DWygwWrNie+vXCuvVPfmSGKxFRm2n86nGoaDlNOIwOtAHlnvJIXcy/I8ZY5w9SbkEeZJIMTeK1E/6YqGUEbBH0yhrV+UVZzYuIgT8FmCiLSFgbuq5n+M7oG9Hj8FRByV/4jO1eXa+itjvrPUdavhpDwOXBl2gFXDgcMHIv9XakTjvm0k0NXP2yBme1keK3sLLqTCTAFvg1AiqoMM1QDDS6z5D+Z2Mam/WLBetSUOj/dsUxHSZvQBL/o8YAyT+wBuLeeaSbEBncKFG+6HcVo3Z+5EDkWiyeD3wCR/qj5OhwfbAfhW5Y+JQ+IQ2/OHqcRv8dUuvkAQV9szd1iaVRVceHT4cvDmc6UG7OmHrIXe18vbDDw843ReoefAwoOKr05nTWwckLIH6TpU7tsVRfClJ+U2KAxD0gf6UIpm7U5AV8q/QKDuL+7LPGqrBXCyhWAue1kBI/zbi45RkLBp2s0aui+MwDcG1xTzd6mu8Fi3Bu8765yDbX/X17xY=}
